const devList = [
	{ uri: "http://cms.dev.hahavideos.net", ip: "172.21.1.18", title: "MGP_Video - cms" },
	{ uri: "http://www.dev.hahavideos.net", ip: "172.21.1.18", title: "MGP_Video - www" },
	{ uri: "http://admin.dev.nihonex.jp", ip: "172.21.1.11", title: "Currency - cms" },
	{ uri: "http://dev.nihonex.jp", ip: "172.21.1.11", title: "Currency - www" },
	{ uri: "http://www.dev.veryrich.hk", ip: "172.21.1.14", title: "Currency_hk - cms" },
	{ uri: "http://cms.dev.veryrich.hk", ip: "172.21.1.14", title: "Currency_hk - www" },
	{ uri: "http://signup.dev.megadates.org/uk/a/1", ip: "172.21.1.11", title: "Landing - megadates" },
	{ uri: "http://signup.dev.love2date.in/uk/a/1", ip: "172.21.1.11", title: "Landing - love2date" },
	{ uri: "http://signup.dev.lovedating.co/uk/a/1", ip: "172.21.1.11", title: "Landing - lovedating" },
	{ uri: "http://signup.dev.bestvipdating.com/uk/a/1", ip: "172.21.1.11", title: "Landing - bestvipdating" },
	{ uri: "http://signup.dev.acedating.net/uk/a/1", ip: "172.21.1.11", title: "Landing - bestvipdating" },
	{ uri: "http://admin.dev.megadates.org", ip: "172.21.1.11", title: "Landing - cms" },
	// { uri: "http://cms.dev.topkaitori.jp", ip: "172.21.1.11", title: "Second Hand - cms" },
	// { uri: "http://www.dev.topkaitori.jp", ip: "172.21.1.11", title: "Second Hand - www" },
	{ uri: "http://uk.dev.megadates.org/index.php ", ip: "172.21.1.18", title: "Dating - megadates" },
	{ uri: "http://dev.acegames.co", ip: "172.21.1.11", title: "acegames" },
	{ uri: "http://dev.admin.mobilegamepass.com", ip: "172.21.1.11", title: "mobilegamepass - admin" },
	{ uri: "http://dev.bestgamesforever.net", ip: "172.21.1.11", title: "bestgamesforever" },
	{ uri: "http://dev.gamewonderland.me", ip: "172.21.1.11", title: "gamewonderland" },
	{ uri: "http://dev.gamezhouse.com", ip: "172.21.1.11", title: "gamezhouse" },
	{ uri: "http://dev.maxigamez.com", ip: "172.21.1.11", title: "maxigamez" },
	{ uri: "http://dev.mobilegamepass.com", ip: "172.21.1.11", title: "mobilegamepass - www" },
	{ uri: "http://dev.premiumgamez.com", ip: "172.21.1.11", title: "premiumgamez - www" },
	{ uri: "http://dev.totalgamingsite.com", ip: "172.21.1.11", title: "totalgamingsite" },
	{ uri: "http://dev.unlimitedgames4you.net", ip: "172.21.1.11", title: "unlimitedgames4you" },
	{ uri: "http://pay.dev.uploadable.com", ip: "172.21.1.12", title: "uploadable" },
	{ uri: "http://cs.dev.bestvipgames.com", ip: "172.21.1.12", title: "bestvipgames - cs" },
	{ uri: "http://cs.dev.mobilegamepass.com", ip: "172.21.1.12", title: "mobilegamepass - cs" },
	{ uri: "http://cs.dev.premiumgamez.com ", ip: "172.21.1.12", title: "premiumgamez - cs" },
];

module.exports = {
	DEV_LIST: devList
};